CognitoUserPool:
  Type: "AWS::Cognito::UserPool"
  Properties:
    MfaConfiguration: OFF
    UserPoolName: ${self:custom.userPoolName}
    UsernameAttributes:
      - email
    Policies:
      PasswordPolicy:
        MinimumLength: 6
        RequireLowercase: False
        RequireNumbers: True
        RequireSymbols: False
        RequireUppercase: True
    AutoVerifiedAttributes: ["email"]